name: Deploy to Firebase Hosting on merge to main

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install  # Modify this line based on your project's needs

      - name: Build
        run: npm run build  # Modify this line based on your project's build script

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
