name: Deploy to Firebase Hosting on merge to main

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set Up GCP Credentials
        run: |
         echo "${{ secrets.GCP_SA_KEY }}" > /opt/gcp_key.json
         cat /opt/gcp_key.json  # Temporarily add this line to debug the file content
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
